import express from 'express';
import cors from 'cors';
import { db } from './db';
import { products, orders, orderItems } from './db/schema';
import { eq, desc } from 'drizzle-orm';

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// --- GET ALL PRODUCTS ---
app.get('/api/products', async (req, res) => {
  try {
    const allProducts = await db.select().from(products);
    // Transform data to match frontend structure if needed
    // For now, we assume the frontend sends/receives compatible structure
    res.json(allProducts);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Failed to fetch products' });
  }
});

// --- CREATE ORDER (Guest Checkout) ---
app.post('/api/orders', async (req, res) => {
  const { customerName, phone, address, items, subtotal, deliveryCharge, totalPayable, orderId } = req.body;

  try {
    // 1. Create Order
    await db.insert(orders).values({
      id: orderId, // Using the ID generated by frontend or generating a new one here
      customerName,
      phone,
      address,
      status: 'Taken',
      totalAmount: totalPayable,
      deliveryCharge,
    });

    // 2. Create Order Items
    const orderItemsData = items.map((item: any) => ({
      orderId: orderId,
      productId: item.id,
      quantity: item.quantity,
      priceAtPurchase: parseFloat(item.price.replace('৳', '')), // Ensure we strip currency symbol
    }));

    await db.insert(orderItems).values(orderItemsData);

    res.json({ success: true, orderId });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Failed to create order' });
  }
});

// --- TRACK ORDER ---
app.post('/api/orders/track', async (req, res) => {
  const { orderId, phone } = req.body;

  try {
    const order = await db.query.orders.findFirst({
      where: (orders, { eq, and }) => and(eq(orders.id, orderId), eq(orders.phone, phone)),
      with: {
        items: {
          with: {
            product: true
          }
        }
      }
    });

    if (!order) {
      return res.status(404).json({ error: "Order not found or phone number incorrect." });
    }

    // Transform DB result back to frontend OrderConfirmationData format
    const formattedOrder = {
      orderId: order.id,
      status: order.status,
      customerName: order.customerName,
      shippingAddress: order.address,
      estimatedDelivery: '2 Days', // Static for now
      items: order.items.map((item) => ({
        ...item.product, // Spread product details
        quantity: item.quantity,
        price: `৳${item.priceAtPurchase}`
      })),
      subtotal: order.totalAmount - order.deliveryCharge, // Approximate
      deliveryCharge: order.deliveryCharge,
      discountAmount: 0,
      totalPayable: order.totalAmount,
      paymentMethod: 'Cash on Delivery'
    };

    res.json(formattedOrder);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Server error' });
  }
});

app.listen(PORT, () => {
  console.log(`🚀 Server running on http://localhost:${PORT}`);
});